services:
  migrations:
    image: mediacms/mediacms:latest
    working_dir: /home/mediacms.io/mediacms/
    entrypoint: ["/bin/sh", "-c"]
    command: "./deploy/docker/prestart.sh"
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'carnivash@gmail.com'
      ADMIN_PASSWORD: 'proj2501'
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  web:
    image: mediacms/mediacms:latest
    entrypoint: ["/bin/sh", "-c"]
    command: "uwsgi --ini ./deploy/docker/uwsgi.ini"
    working_dir: /home/mediacms.io/mediacms/
    ports:
      - "8004:80"
    volumes:
      - /home/alexander/mediacms:/home/mediacms.io/mediacms/
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations

  celery_beat:
    image: mediacms/mediacms:latest
    entrypoint: ["/bin/sh", "-c"]
    command: "celery -A mediacms beat -l info"
    working_dir: /home/mediacms.io/mediacms/
    volumes:
      - /home/alexander/mediacms:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - redis

  celery_worker:
    image: mediacms/mediacms:latest
    entrypoint: ["/bin/sh", "-c"]
    command: "celery -A mediacms worker -l info"
    working_dir: /home/mediacms.io/mediacms/
    volumes:
      - /home/alexander/mediacms:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations

  db:
    image: postgres:17.2-alpine
    volumes:
      - /home/alexander/mediacms/postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
      TZ: America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 3
